### ISSUE TITLE
faid to access the link of the paper.

### ISSUE THREAD

**Issue by YrralH** [facebookresearch/real-acoustic-fields#1]
Hello~
Looking forward to seeing the paper. 
The current link <https://facebookresearch.github.io/real-acoustic-fields/static/docs/real-acoustic-fields.pdf> seems to be invalid(404).

**Comment by IFICL** [comment]
Hi,

Thank you for your interest. We will put the paper on arXiv and upload the paper to the website link within next week.

**Comment by IFICL** [comment]
Hi, our paper is online now.
