### ISSUE TITLE
rx/tx position meaning

### ISSUE THREAD

**Issue by ZitongLan** [facebookresearch/real-acoustic-fields#2]
In each rx.txt, do the three numbers correspond to their position, in **meter** unit? Does it correspond to xyz permutation or xzy permutation? And where can I find the rotation direction of the receiver? 

In each tx.txt, what do the seven number correspond to?

**Comment by isrish** [comment]
Hi, please refer to the updated readme for more details. In rx.txt, the numbers denote the 3D location (xyz) in meters. In tx.txt, the first four numbers represent the transmitter's orientation in quaternion format (xyzw), and  the last three numbers indicate the 3D position (xyz) in meters.
