### ISSUE TITLE
Details of data split

### ISSUE THREAD

**Issue by YoshikiMas** [facebookresearch/real-acoustic-fields#7]
Hi, thank you for publishing a great dataset for spatial audio!

Similar to others, I'd like to reproduce the results in the paper, but I couldn't find the details of the data split. Could you share information in addition to the train/valid/test ratio?
The information would be helpful in sharing the same data split across papers and using RAF as a benchmark.

Thank you.

**Comment by isrish** [comment]
Here: https://github.com/facebookresearch/real-acoustic-fields/tree/main/data-split

**Comment by YoshikiMas** [comment]
Thank you for your clarification.

**Comment by ChillCoing** [comment]
Hi @YoshikiMas  are you able to reproduce the result? both on NAF and INRAS

**Comment by YoshikiMas** [comment]
Hi @ChillCoing, I didn't try the shared split yet. But, with my own random split, I couldn't reproduce the scores in the paper even with [the discussed scoring scripts](https://github.com/facebookresearch/real-acoustic-fields/issues/4), especially the RT60 error.
